"""Report rendering: self-contained HTML, Markdown and JSON."""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import config
from .db import Scan

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
_SEV_COLOR = {
    "CRITICAL": "#b3123a",
    "HIGH": "#d4531e",
    "MEDIUM": "#b8860b",
    "LOW": "#2b6cb0",
    "INFO": "#5a6272",
}
_CATEGORY_LABEL = {
    "sast": "Code flaw",
    "secret": "Exposed secret",
    "dependency": "Vulnerable dependency",
    "iac": "Infrastructure misconfiguration",
}


def report_paths(scan_id: str) -> dict[str, Path]:
    base = config.REPORT_DIR / scan_id
    return {
        "html": base / "report.html",
        "md": base / "report.md",
        "json": base / "report.json",
    }


def write_all(scan: Scan) -> dict[str, Path]:
    paths = report_paths(scan.id)
    paths["html"].parent.mkdir(parents=True, exist_ok=True)
    data = scan.to_dict(include_findings=True)
    paths["json"].write_text(json.dumps(data, indent=2), encoding="utf-8")
    paths["md"].write_text(render_markdown(data), encoding="utf-8")
    paths["html"].write_text(render_html(data), encoding="utf-8")
    return paths


# --------------------------------------------------------------------- shared


def _visible(data: dict) -> list[dict]:
    """Findings worth printing: everything Claude did not dismiss."""
    out = [f for f in data.get("findings", []) if f.get("verdict") != "false_positive"]
    out.sort(
        key=lambda f: (
            SEVERITY_ORDER.index(f["effective_severity"])
            if f["effective_severity"] in SEVERITY_ORDER
            else 99,
            f.get("file_path", ""),
            f.get("line_start", 0),
        )
    )
    return out


def _dismissed(data: dict) -> list[dict]:
    return [f for f in data.get("findings", []) if f.get("verdict") == "false_positive"]


def _generated_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ------------------------------------------------------------------ markdown


def render_markdown(data: dict) -> str:
    summary = data.get("summary") or {}
    counts = summary.get("counts") or {}
    findings = _visible(data)
    dismissed = _dismissed(data)

    lines = [
        "# VAPT Report",
        "",
        "**Repository:** " + data["repo_url"],
        "**Branch:** " + (data.get("branch") or "default")
        + "  |  **Commit:** " + (data.get("commit_sha") or "")[:12],
        "**Generated:** " + _generated_at(),
        "**Risk score:** {}/100 (grade {})".format(
            summary.get("risk_score", 0), summary.get("grade", "-")
        ),
        "",
        "## Findings at a glance",
        "",
        "| Severity | Count |",
        "| --- | ---: |",
    ]
    for severity in SEVERITY_ORDER:
        lines.append("| {} | {} |".format(severity, counts.get(severity, 0)))
    lines += [
        "",
        "- Confirmed by AI triage: {}".format(summary.get("confirmed", 0)),
        "- Needs human review: {}".format(summary.get("needs_review", 0)),
        "- Dismissed as false positives: {}".format(summary.get("dismissed", 0)),
        "- Not triaged: {}".format(summary.get("untriaged", 0)),
        "",
    ]

    if data.get("executive_summary"):
        lines += [data["executive_summary"], ""]

    lines += ["## Scanner coverage", "", "| Scanner | Status | Findings | Duration |",
              "| --- | --- | ---: | ---: |"]
    for run in data.get("scanner_runs") or []:
        note = " - " + run["message"] if run.get("message") else ""
        lines.append(
            "| {} | {}{} | {} | {}s |".format(
                run.get("name"), run.get("status"), note,
                run.get("findings", 0), run.get("duration", 0),
            )
        )
    lines.append("")

    lines += ["## Detailed findings", ""]
    if not findings:
        lines.append("No findings survived triage.")
    for i, f in enumerate(findings, start=1):
        lines += _markdown_finding(i, f)

    if dismissed:
        lines += ["", "## Dismissed as false positives", ""]
        for f in dismissed:
            lines.append(
                "- **{}** at `{}` - {}".format(
                    f["title"], _loc(f), f.get("triage_rationale", "")
                )
            )

    lines += [
        "",
        "---",
        "",
        "*Static analysis of source code only. No running application was tested. "
        "Generated by vapt-ai.*",
    ]
    return "\n".join(lines)


def _markdown_finding(number: int, f: dict) -> list[str]:
    out = [
        "### {}. [{}] {}".format(number, f["effective_severity"], f["title"]),
        "",
        "- **Type:** {}".format(_CATEGORY_LABEL.get(f["category"], f["category"])),
        "- **Location:** `{}`".format(_loc(f)),
        "- **Detected by:** {}{}".format(
            f["scanner"],
            " (corroborated by " + ", ".join(f["corroborated_by"]) + ")"
            if f.get("corroborated_by") else "",
        ),
        "- **Rule:** `{}`".format(f.get("rule_id", "")),
    ]
    if f.get("cwe"):
        out.append("- **CWE:** " + ", ".join(f["cwe"]))
    if f.get("package"):
        out.append(
            "- **Package:** {} {} (fixed in {})".format(
                f["package"], f.get("installed_version", ""),
                f.get("fixed_version") or "no fix published",
            )
        )
    if f.get("triaged"):
        out.append(
            "- **AI verdict:** {} ({} confidence)".format(f["verdict"], f["confidence"])
        )
    out.append("")

    if f.get("description"):
        out += [f["description"].strip(), ""]
    if f.get("attack_scenario"):
        out += ["**Attack scenario.** " + f["attack_scenario"].strip(), ""]
    if f.get("remediation"):
        out += ["**Remediation.** " + f["remediation"].strip(), ""]
    if f.get("code_snippet"):
        out += ["```", f["code_snippet"].rstrip(), "```", ""]
    if f.get("reference"):
        out += ["Reference: " + f["reference"], ""]
    return out


def _loc(f: dict) -> str:
    if not f.get("file_path"):
        return "-"
    if f.get("line_start"):
        return "{}:{}".format(f["file_path"], f["line_start"])
    return f["file_path"]


# ---------------------------------------------------------------------- html


def render_html(data: dict) -> str:
    summary = data.get("summary") or {}
    counts = summary.get("counts") or {}
    findings = _visible(data)
    dismissed = _dismissed(data)
    e = html.escape

    chips = "".join(
        '<div class="chip" style="--c:{color}">'
        '<span class="n">{n}</span><span class="l">{sev}</span></div>'.format(
            color=_SEV_COLOR[s], n=counts.get(s, 0), sev=s.title()
        )
        for s in SEVERITY_ORDER
    )

    scanner_rows = "".join(
        "<tr><td>{}</td><td><span class='status {}'>{}</span></td>"
        "<td class='num'>{}</td><td class='num'>{}s</td><td class='muted'>{}</td></tr>".format(
            e(str(r.get("name"))), e(str(r.get("status"))), e(str(r.get("status"))),
            r.get("findings", 0), r.get("duration", 0), e(str(r.get("message", ""))),
        )
        for r in data.get("scanner_runs") or []
    )

    finding_blocks = "".join(_html_finding(i, f) for i, f in enumerate(findings, 1))
    if not findings:
        finding_blocks = "<p class='muted'>No findings survived triage.</p>"

    dismissed_block = ""
    if dismissed:
        items = "".join(
            "<li><strong>{}</strong> <code>{}</code><br><span class='muted'>{}</span></li>".format(
                e(f["title"]), e(_loc(f)), e(f.get("triage_rationale", ""))
            )
            for f in dismissed
        )
        dismissed_block = (
            "<h2>Dismissed as false positives</h2><ul class='dismissed'>"
            + items + "</ul>"
        )

    narrative = _markdown_to_html(data.get("executive_summary") or "")
    usage = data.get("triage_usage") or {}
    usage_line = ""
    if usage.get("requests"):
        usage_line = (
            "AI triage: {} requests, {:,} input / {:,} output tokens, "
            "{:,} served from cache, est. ${}".format(
                usage["requests"], usage.get("input_tokens", 0),
                usage.get("output_tokens", 0), usage.get("cache_read_tokens", 0),
                usage.get("estimated_cost_usd", 0),
            )
        )

    warnings = "".join(
        "<div class='warn'>{}</div>".format(e(str(msg)))
        for msg in (usage.get("errors") or [])
    )

    return _HTML_TEMPLATE.format(
        title=e(data["repo_url"].rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")),
        repo=e(data["repo_url"]),
        branch=e(data.get("branch") or "default"),
        commit=e((data.get("commit_sha") or "")[:12]),
        generated=_generated_at(),
        languages=e(", ".join(data.get("languages") or []) or "unknown"),
        score=summary.get("risk_score", 0),
        grade=e(str(summary.get("grade", "-"))),
        grade_color=_grade_color(str(summary.get("grade", "-"))),
        chips=chips,
        confirmed=summary.get("confirmed", 0),
        needs_review=summary.get("needs_review", 0),
        dismissed_count=summary.get("dismissed", 0),
        untriaged=summary.get("untriaged", 0),
        warnings=warnings,
        narrative=narrative,
        scanner_rows=scanner_rows,
        findings=finding_blocks,
        dismissed_block=dismissed_block,
        usage_line=e(usage_line),
    )


def _html_finding(number: int, f: dict) -> str:
    e = html.escape
    severity = f["effective_severity"]
    color = _SEV_COLOR.get(severity, "#5a6272")

    meta = [
        "<span class='tag'>{}</span>".format(e(_CATEGORY_LABEL.get(f["category"], f["category"]))),
        "<span class='tag'>{}</span>".format(e(f["scanner"])),
    ]
    for cwe in f.get("cwe") or []:
        meta.append("<span class='tag'>{}</span>".format(e(str(cwe))))
    if f.get("corroborated_by"):
        meta.append(
            "<span class='tag ok'>confirmed by {}</span>".format(
                e(", ".join(f["corroborated_by"]))
            )
        )
    if f.get("triaged"):
        cls = {"true_positive": "bad", "needs_review": "warnv"}.get(f["verdict"], "")
        meta.append(
            "<span class='tag {}'>{} / {} confidence</span>".format(
                cls, e(f["verdict"].replace("_", " ")), e(f["confidence"])
            )
        )

    sections = []
    if f.get("description"):
        sections.append("<p>{}</p>".format(e(f["description"].strip()).replace("\n", "<br>")))
    if f.get("package"):
        sections.append(
            "<p class='pkg'><strong>{}</strong> {} &rarr; fixed in {}</p>".format(
                e(f["package"]), e(f.get("installed_version", "")),
                e(f.get("fixed_version") or "no fix published"),
            )
        )
    if f.get("attack_scenario"):
        sections.append(
            "<div class='box attack'><h4>Attack scenario</h4><p>{}</p></div>".format(
                e(f["attack_scenario"].strip())
            )
        )
    if f.get("remediation"):
        sections.append(
            "<div class='box fix'><h4>Remediation</h4><p>{}</p></div>".format(
                e(f["remediation"].strip())
            )
        )
    if f.get("code_snippet"):
        sections.append("<pre><code>{}</code></pre>".format(e(f["code_snippet"].rstrip())))
    if f.get("reference"):
        sections.append(
            "<p class='muted'>Reference: <a href='{0}' rel='noreferrer noopener'>{0}</a></p>".format(
                e(f["reference"])
            )
        )

    return (
        "<article class='finding' style='--c:{color}'>"
        "<header><span class='sev'>{sev}</span>"
        "<h3>{num}. {title}</h3>"
        "<code class='loc'>{loc}</code></header>"
        "<div class='meta'>{meta}</div>{body}</article>"
    ).format(
        color=color, sev=e(severity), num=number, title=e(f["title"]),
        loc=e(_loc(f)), meta="".join(meta), body="".join(sections),
    )


def _grade_color(grade: str) -> str:
    return {
        "A": "#1a7f4b", "B": "#3f8f3f", "C": "#b8860b",
        "D": "#d4531e", "E": "#c0392b", "F": "#b3123a",
    }.get(grade, "#5a6272")


def _markdown_to_html(text: str) -> str:
    """Just enough Markdown for the narrative Claude returns: headings, lists,
    bold and paragraphs. Everything is escaped first."""
    if not text:
        return ""
    import re

    out: list[str] = []
    list_open = False
    for line in html.escape(text).splitlines():
        stripped = line.strip()
        if not stripped:
            if list_open:
                out.append("</ol>" if list_open == "ol" else "</ul>")
                list_open = False
            continue

        heading = re.match(r"^(#{2,4})\s+(.*)$", stripped)
        if heading:
            if list_open:
                out.append("</ol>" if list_open == "ol" else "</ul>")
                list_open = False
            level = min(len(heading.group(1)) + 1, 5)
            out.append("<h{0}>{1}</h{0}>".format(level, _inline(heading.group(2))))
            continue

        ordered = re.match(r"^\d+[.)]\s+(.*)$", stripped)
        bullet = re.match(r"^[-*]\s+(.*)$", stripped)
        if ordered or bullet:
            want = "ol" if ordered else "ul"
            if list_open != want:
                if list_open:
                    out.append("</ol>" if list_open == "ol" else "</ul>")
                out.append("<" + want + ">")
                list_open = want
            out.append("<li>{}</li>".format(_inline((ordered or bullet).group(1))))
            continue

        if list_open:
            out.append("</ol>" if list_open == "ol" else "</ul>")
            list_open = False
        out.append("<p>{}</p>".format(_inline(stripped)))

    if list_open:
        out.append("</ol>" if list_open == "ol" else "</ul>")
    return "".join(out)


def _inline(text: str) -> str:
    import re
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VAPT Report - {title}</title>
<style>
  :root {{
    --bg: #f7f7f5; --card: #ffffff; --ink: #1c1c1a; --muted: #6b7280;
    --line: #e4e4e0; --accent: #b3123a;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #17171a; --card: #1f1f23; --ink: #ececea; --muted: #9ca3af;
      --line: #32323a;
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.6 ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif;
  }}
  .wrap {{ max-width: 960px; margin: 0 auto; padding: 32px 20px 80px; }}
  h1 {{ font-size: 1.7rem; margin: 0 0 6px; letter-spacing: -0.02em; }}
  h2 {{ font-size: 1.15rem; margin: 40px 0 14px; letter-spacing: -0.01em;
        border-bottom: 1px solid var(--line); padding-bottom: 8px; }}
  h3 {{ font-size: 1rem; margin: 0; }}
  h4 {{ font-size: .8rem; margin: 0 0 4px; text-transform: uppercase;
        letter-spacing: .06em; color: var(--muted); }}
  .muted {{ color: var(--muted); font-size: .88rem; }}
  code {{ font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; font-size: .85em; }}
  a {{ color: inherit; }}

  .head {{ display: flex; gap: 20px; align-items: flex-start; flex-wrap: wrap;
           justify-content: space-between; }}
  .grade {{ width: 76px; height: 76px; border-radius: 16px; display: grid;
            place-items: center; color: #fff; font-size: 2.1rem; font-weight: 700;
            background: {grade_color}; flex: none; }}
  .score {{ font-size: .8rem; text-align: center; color: var(--muted); margin-top: 4px; }}

  .chips {{ display: flex; gap: 10px; flex-wrap: wrap; margin: 24px 0; }}
  .chip {{ flex: 1 1 110px; background: var(--card); border: 1px solid var(--line);
           border-left: 4px solid var(--c); border-radius: 10px; padding: 12px 14px; }}
  .chip .n {{ display: block; font-size: 1.6rem; font-weight: 700; line-height: 1; }}
  .chip .l {{ font-size: .76rem; color: var(--muted); text-transform: uppercase;
              letter-spacing: .06em; }}

  .tally {{ display: flex; gap: 18px; flex-wrap: wrap; font-size: .88rem;
            color: var(--muted); margin-bottom: 8px; }}
  .tally b {{ color: var(--ink); }}

  .warn {{ background: #fff4e5; border: 1px solid #f0c992; color: #7a4a05;
           padding: 10px 14px; border-radius: 8px; margin: 10px 0; font-size: .88rem; }}
  @media (prefers-color-scheme: dark) {{
    .warn {{ background: #3a2c10; border-color: #6b5320; color: #f0d9a8; }}
  }}

  table {{ width: 100%; border-collapse: collapse; font-size: .9rem; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); }}
  th.num {{ text-align: right; }}
  td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .status {{ font-size: .78rem; padding: 2px 8px; border-radius: 99px;
             background: var(--line); }}
  .status.ok {{ background: #d9f0e1; color: #14532d; }}
  .status.error {{ background: #fadcdc; color: #7f1d1d; }}
  .status.skipped {{ background: #eceaf2; color: #4b4b5a; }}

  .finding {{ background: var(--card); border: 1px solid var(--line);
              border-left: 4px solid var(--c); border-radius: 10px;
              padding: 16px 18px; margin-bottom: 14px; }}
  .finding header {{ display: flex; gap: 10px; align-items: baseline; flex-wrap: wrap; }}
  .sev {{ background: var(--c); color: #fff; font-size: .68rem; font-weight: 700;
          letter-spacing: .08em; padding: 3px 8px; border-radius: 4px; }}
  .loc {{ color: var(--muted); margin-left: auto; }}
  .meta {{ display: flex; gap: 6px; flex-wrap: wrap; margin: 10px 0; }}
  .tag {{ font-size: .73rem; background: var(--line); color: var(--muted);
          padding: 2px 8px; border-radius: 99px; }}
  .tag.ok {{ background: #d9f0e1; color: #14532d; }}
  .tag.bad {{ background: #fadcdc; color: #7f1d1d; }}
  .tag.warnv {{ background: #fdefd2; color: #7a4a05; }}
  .box {{ border-radius: 8px; padding: 10px 12px; margin: 10px 0; }}
  .box.attack {{ background: rgba(179,18,58,.07); }}
  .box.fix {{ background: rgba(26,127,75,.09); }}
  .box p {{ margin: 0; }}
  pre {{ background: var(--bg); border: 1px solid var(--line); border-radius: 8px;
         padding: 12px; overflow-x: auto; font-size: .82rem; line-height: 1.45; }}
  .dismissed li {{ margin-bottom: 8px; }}
  footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--line);
            color: var(--muted); font-size: .84rem; }}
</style></head><body><div class="wrap">

<div class="head">
  <div>
    <h1>VAPT Report</h1>
    <div class="muted">{repo}</div>
    <div class="muted">branch <code>{branch}</code> &middot; commit <code>{commit}</code></div>
    <div class="muted">{languages} &middot; generated {generated}</div>
  </div>
  <div>
    <div class="grade">{grade}</div>
    <div class="score">risk {score}/100</div>
  </div>
</div>

<div class="chips">{chips}</div>
<div class="tally">
  <span><b>{confirmed}</b> confirmed</span>
  <span><b>{needs_review}</b> need review</span>
  <span><b>{dismissed_count}</b> dismissed</span>
  <span><b>{untriaged}</b> not triaged</span>
</div>
{warnings}

{narrative}

<h2>Scanner coverage</h2>
<table><thead><tr><th>Scanner</th><th>Status</th><th class="num">Findings</th>
<th class="num">Duration</th><th>Note</th></tr></thead>
<tbody>{scanner_rows}</tbody></table>

<h2>Detailed findings</h2>
{findings}

{dismissed_block}

<footer>
  <p>Static analysis of source code only &mdash; no running application was tested.
  Findings marked &ldquo;need review&rdquo; require a human decision.</p>
  <p>{usage_line}</p>
  <p>Generated by vapt-ai.</p>
</footer>
</div></body></html>
"""
